define([
    './Account',
    './Calendar',
    './Chat',
    './Documents',
    './Friends',
    './Glossary',
    './Main',
    './Message',
    './Notebook',
    './Passwords',
    './Purchases',
    './Photos',
    './Wishes',
], function () {});